[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "cloudinary>=1.44.1",
    "flask>=3.1.2",
    "flask-wtf>=1.2.2",
    "psycopg2-binary>=2.9.11",
    "werkzeug>=3.1.4",
]
